name: catalogo_produtos
description: Catálogo de produtos em Flutter inspirado no WhatsApp Business.
publish_to: "none" # não publica no pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  shared_preferences: ^2.1.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/placeholder.png
    - assets/notebook.jpg
    - assets/camiseta.jpg
    - assets/livro.jpg
